### ISSUE TITLE
Launch SDAT

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/AA-Credit-and-Appeals#1]
When the user right clicks to view SDAT information for a record in search results the following message appears:

 
![sdat](https://cloud.githubusercontent.com/assets/4129185/24276164/0e9f8320-100b-11e7-8487-e06f4db07724.PNG)

**Comment by dhenry-KCI** [comment]
update website url with http://dat.maryland.gov/Pages/default.aspx

**Comment by BC89** [comment]
seems that this is no longer possible with the way SDAT has been coded and, in fact, is no longer prohibited as stated on the search page. We can throw them into the search page for now but to reverse engineer is not allowed.
