### ISSUE TITLE
Credit Activity - Generate Packet

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/AA-Credit-and-Appeals#10]
When the user selects "Generate Packet" after selecting a model resolution the system presents the user a "generating packet" message, the spins and doesn't resolve.

![generate packet](https://user-images.githubusercontent.com/4129185/36040975-1de8bbac-0d95-11e8-9868-be97cd0e8c06.PNG)

To recreate:
Create a credit
Checkoff all review bullets
Load model
Select charge code
Save model
Select Resolution
Save Resolution
Generate Packet (continues to spin)

**Comment by ehsan67** [comment]
@dhenry-KCI  the problem is application doesn't load the model which is because there is no Resolution_Model for the created review. I tried to find where we create Resolution_model and couldn't find it. How do we populate that table? @BC89

**Comment by ehsan67** [comment]
The Arcgis service was down, now it is running but still doesn' works because it is not able to access this file \\kci-md1000ctrl\data\Test\ResponseDocument\draftresponse.doc'

@dhenry-KCI

**Comment by BC89** [comment]
That directory no longer exists. Frank has moved the entire drive. Update the config to \\spsvm\P055\Test<file://spsvm/P055/Test>

**Comment by ehsan67** [comment]
fixed

**Comment by dhenry-KCI** [comment]
confirmed fixed in KCI dev.
