### ISSUE TITLE
Associated Account - Review Tab

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/AA-Credit-and-Appeals#11]
When the user attempts to perform a Property Research Review (within Review Tab), whenever the user clicks on one of the radio buttons (correct or incorrect), the UI shifts down to the Credit/Fee portion of the Review tab. 

To recreate select Reviewer Assigned = Dustin, select Ronald Begin. The second associated record named Hawthorne Woods LTD is causing the issue (The same problem didn't occur for the other associated accounts).

**Comment by BC89** [comment]
Can't reproduce and am not sure Issue is up to date as there was discussion about a tablet-only possibility. No inconsistencies on my laptop.
