### ISSUE TITLE
Create Activity - Holds Form Type Value = 1

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/AA-Credit-and-Appeals#12]
When the user creates a new Credit/Appeal the system will populate the form type = 1, if the user selects Type = Call or In-person, then switches type selection back to Form.

Steps to recreate:
1. Select record and create new activity
2. Select Type = "Call" or "In-Person"
3. Select Type = "Form"

a "1" is populated in the form type field.

**Comment by ehsan67** [comment]
fixed

**Comment by dhenry-KCI** [comment]
Confirmed fixed in KCI Dev
