### ISSUE TITLE
Load Model - Yes / No

### ISSUE THREAD

**Issue by ehsan67** [dhenry-KCI/AA-Credit-and-Appeals#13]
When the user clicks "Load Model" , and selects "Yes", the system should first load a saved model (if existing), if no model exists then the system should pull the default values from the web services. when the user selects "no" the system should automatically load the default web service values.

**Comment by ehsan67** [comment]
fixed

**Comment by dhenry-KCI** [comment]
Confirmed fixed in KCI dev
