### ISSUE TITLE
Associated Appeal / Credit

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/AA-Credit-and-Appeals#2]
When the user creates an associated appeal/credit related to an existing appeal/credit, the system populates the fiscal year field = 0. 

To Fix: Fiscal year should default to the same year as the parent record.

![fiscal year](https://cloud.githubusercontent.com/assets/4129185/24276430/23c32372-100d-11e7-8446-0d4e12a73529.PNG)

**Comment by dhenry-KCI** [comment]
Fiscal year for child records should = fiscal year of the parent record.

**Comment by BC89** [comment]
Fixed

**Comment by dhenry-KCI** [comment]
Confirmed
