### ISSUE TITLE
Create Account

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/AA-Credit-and-Appeals#3]
When the user creates an appeal/credit for an existing accounting, the system presents the user an error that the account already exists.

The system should present the user from creating a new appeal / credit for some reporting year, but allow for creation of appeal or credit in subsequent reporting years.

![create account](https://cloud.githubusercontent.com/assets/4129185/24276623/4e73c350-100e-11e7-97a3-d6c06abce31f.PNG)

**Comment by dhenry-KCI** [comment]
User should be able to create an appeal or credit in same year
Check appeal creation logic- is there a status preventing the creation of an appeal?

**Comment by BC89** [comment]
There is a very explicit piece of code checking and prohibiting creation of multiple reviews:

Review existReview = context.Reviews
                            .AsNoTracking()
                            .Where(n => n.Tax_ID == Tax_ID
                                && n.Application_ID == Application_ID
                                && n.Is_Active == true
                                && n.Resolution_ID == 1
                            )
                            .FirstOrDefault();

                        if (existReview != null)
                        {
                            var response = new HttpResponseMessage(HttpStatusCode.OK);
                            response.Content = new StringContent("Review Not Created. Existing Account - " + Tax_ID, System.Text.Encoding.UTF8, "text/plain");
                            return response;
                        }
