### ISSUE TITLE
Create Activity - Form Type - Not Recognizing Path

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/AA-Credit-and-Appeals#9]
When the user creates a new appeal or credit and selects "Type" = form, and clicks save the system presents the error, "the network path was not found.\r\n"

To recreate, select an account , create an appeal or credit, populate with information in the screenshot below. Then hit click save.
![capture _activity_formpng](https://user-images.githubusercontent.com/4129185/36039937-f8cb3e1a-0d91-11e8-885f-91a099d60405.PNG)

User receives the following error:

![networkfilepath not found](https://user-images.githubusercontent.com/4129185/36039951-01b2a2ca-0d92-11e8-8a32-9c6345d19f2f.PNG)

**Comment by ehsan67** [comment]
@dhenry-KCI  works for me

**Comment by dhenry-KCI** [comment]
@ehsan67 , Let's talk tomorrow morning. I recreate the issue on a different account.

![anne arundel_networkpath](https://user-images.githubusercontent.com/4129185/36083661-e07a3e7c-0f82-11e8-95a9-9a6c090be67d.PNG)

**Comment by ehsan67** [comment]
fixed

**Comment by dhenry-KCI** [comment]
Confirmed fixes in KCI dev
